language: r
warnings_are_errors: true
sudo: false
os:
- linux
- osx
cache: packages
env:
  global:
  - secure: fiyGwDpuFeKotrOqSsRpHr8f3eAjK3pfUBoW7PIqa4rAzuvPR2Ft2j/a2EvsuPlXwxsb7i9pjtbSBXIHoLngCEJ6kDNOCPeKCLNGW8SEWImQC18ThNcCOrD8rdgdON3IeZbS0mWWJqfK6CUELeuZAEt2pqlmLa+0TrNKPW8PTls=
  - secure: Uvjp8cUwYrzVmEVTh36PG10VdEy+uLl6Nx/h47/semGooGO3VjU43ZLrliZ2dTPEQ/7mYuHibte9zpvVV3CE0Ia0xmqqSSzmREwUNVFdQwPFcfUGaZdz6r6sM/9FFksmO4EuD0R5ehbFHz3CJbO+ZXgJAHcItDNmF2fbJL8VdM8=
  - NOT_CRAN="true"
  - secure: n8M2/NfsjK4mALkanOmC3qz+4L5HsyGRZ7cbYJ0ThtWFJVdJVUdiV/chFXFwtVJNO46zTw2+M0PdRV75R0ZQtFo09tw62swXwbnA5BtDeOv/M8skRO6KhYzjYuCrBweKDv+fHlK3h9ia6jOyrdjVgmckDaqI2DTVIETzTapTowg=
  - secure: M/7JgQWLiZDgRb7qsT9STMx7MqKazBCHhznFFTrgs4AS7YXQhtiDbGOL5krZ6Nxfa/jCxdyjAtPmvqGoReS/ughVNVKX33U1yJz1Z+guuzRDvTfTszqaSv67HJS+vaWLpoWMfUVwdCnDYt5qwCz7XGGnBAt/9quS9tcnn9fCTeM=
  - secure: DwuO9/XtPRFfoobQIAT3QCPuq5/Hm8JUxXvkyUhguiKw9vCys7OED5HoUIYx18oxaq8Ldp58KYrAKgXWjihkF/lNFtQQUlyVlHFMN6FZFlwr2ygbE2rU9O0JrwETpCoxUTOKa0i3Tju0QyWvVUzwFuNWWs2+6BLusT34+9A7UvQ=
