# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
    
environment:
  USER:
    secure: XvI9/WqLQ0NkXl296QP543inGADVvohRMeX9D7sKvpQ=
  SECRET:
    secure: pJ6eA2UuIKz0LwktPqC62tVewfpM7NVr8UMKuDNhC1Dh2Ezm7IXkrQC8/av2lHSX
  FTP:
    secure: /Bl8Ao7sIyhKBLZ8rYPFfkn5/P57q3Xld2a9SaY3i0g=
  FTPUSER:
    secure: BkSR4+Pkkc6iAy2F/hlg7PSHY53jp88hLifK3qvV3mi/Bmjxg+NGQEYsHM1k5zlL
  FTPPW:
    secure: J8LA0Uf059mgXeMWGJbI6A==
  NOT_CRAN: true  

